// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi7btU0CFPWmnYXx0KuR8RqAv_S7AZB10',
    appId: '1:398616390707:web:915d68142141c218090746',
    messagingSenderId: '398616390707',
    projectId: 'summer22-final-schedule',
    authDomain: 'summer22-final-schedule.firebaseapp.com',
    storageBucket: 'summer22-final-schedule.appspot.com',
    measurementId: 'G-5ZY8P1ZSYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuC619B6JQeWKsQxx4sRLly6vCLiLeDWY',
    appId: '1:398616390707:android:d4f2111bfa139421090746',
    messagingSenderId: '398616390707',
    projectId: 'summer22-final-schedule',
    storageBucket: 'summer22-final-schedule.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3SLLD_FkNnrRLzH-BDIkFb-f-Sd9WLw0',
    appId: '1:398616390707:ios:369eae354b1e3c94090746',
    messagingSenderId: '398616390707',
    projectId: 'summer22-final-schedule',
    storageBucket: 'summer22-final-schedule.appspot.com',
    iosClientId: '398616390707-ohpc4em93u07f33dh0jm9u5p14p354ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.summer22Final',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3SLLD_FkNnrRLzH-BDIkFb-f-Sd9WLw0',
    appId: '1:398616390707:ios:369eae354b1e3c94090746',
    messagingSenderId: '398616390707',
    projectId: 'summer22-final-schedule',
    storageBucket: 'summer22-final-schedule.appspot.com',
    iosClientId: '398616390707-ohpc4em93u07f33dh0jm9u5p14p354ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.summer22Final',
  );
}
